server:
  port: 8084

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowedCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/posts,/posts/**
          filters:
            - RewritePath=^/posts(?<rest>/?.*)$, /api/posts${rest}

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comments,/comments/**
          filters:
            - RewritePath=^/comments(?<rest>/?.*)$, /api/comments${rest}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
          filters:
            - RewritePath=/reviews/(?<path>.*), /api/reviews/$\{path}

        - id: bookmark-service
          uri: lb://bookmark-service
          predicates:
            - Path=/bookmarks,/bookmarks/**
          filters:
            - RewritePath=^/bookmarks(?<rest>/?.*)$, /api/bookmarks${rest}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications,/notifications/**
          filters:
            - RewritePath=^/notifications(?<rest>/?.*)$, /api/notifications${rest}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
