server:
  port: 8083

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "localhost"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowedCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/posts/**
          filters:
            - RewritePath=/posts/(?<path>.*), /api/posts/$\{path}

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comments/**
          filters:
            - RewritePath=/comments/(?<path>.*), /api/comments/$\{path}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
          filters:
            - RewritePath=/reviews/(?<path>.*), /api/reviews/$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
